# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Stanford CrowdSource Platform
tagline:          'A better crowdsourcing platform'
description:      'Documentation and Guide'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Stanford CrowdResearch Team'
  url:            http://crowdresearch.stanford.edu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/crowdresearch/crowdsource-platform